# Generated by Django 5.0.7 on 2024-10-16 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pgs',
            fields=[
                ('pgname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='futurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=100)),
                ('powerbacup', models.CharField(max_length=100)),
                ('hotwater', models.CharField(max_length=100)),
                ('wifi', models.IntegerField()),
                ('pgname', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='app.pgs')),
            ],
        ),
    ]
